/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during local development and is included here so typecheck has the expected baseline.
